# Generated by Django 4.2.2 on 2023-06-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservacionesMaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.estudiante')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionesLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.profesor')),
            ],
        ),
    ]
