# Generated by Django 4.2.2 on 2023-06-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiitulo', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=252)),
                ('estado', models.CharField(choices=[('b', 'borrador'), ('p', 'publicado'), ('e', 'eliminado')], max_length=1)),
                ('autor', models.CharField(max_length=100)),
                ('creado', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pelucaso')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatoria.convocatoria')),
            ],
        ),
    ]
