# Generated by Django 4.2.2 on 2023-06-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0001_initial'),
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.estudiante'),
        ),
    ]
